### ISSUE TITLE
Error: createElement is not a function

### ISSUE THREAD

**Issue by balduinofernando** [fengyuanchen/vue-barcode#10]
I'm trying to use this package and I'm having an error, createElement is not a function.

I'm using vue 3, Inertiajs,  and Laravel.

**Comment by fengyuanchen** [comment]
Are you sure it is an issue with this component?

**Comment by balduinofernando** [comment]
I was installing the latestte version for vue 2, after installing the alpha version it's working on vue 3, but there's also an issue, it's not rendering the barcode in realtime when i use ean 13 as the format.

**Comment by fengyuanchen** [comment]
For EAN13, you must provide a valid value, e.g.:

```html
<vue-barcode value="5901234123457" :options="{ format: 'EAN13' }"></vue-barcode>
```
