### ISSUE TITLE
大神你好CODE128扫描不出来

### ISSUE THREAD

**Issue by AK47-dadada** [fengyuanchen/vue-barcode#11]
如题
![image](https://user-images.githubusercontent.com/30396595/131470326-813f473e-d1b9-44c4-8d01-d8760178f00a.png)
扫描不出来，就离谱~~~

**Comment by fengyuanchen** [comment]
本组件依赖的条形码生成器是 [JsBarcode](https://github.com/lindell/JsBarcode)：

1. 确认你的参数是不是配置正确的。
2. 去 JsBarcode 搜搜看有问题相同问题反馈。
3. 直接使用 JsBarcode 试试。
4. 如果确有问题，给 JsBarcode 提 bug。
