### ISSUE TITLE
JsBarcode is not a function

### ISSUE THREAD

**Issue by Leon0824** [fengyuanchen/vue-barcode#14]
Hi, I got an error of 'JsBarcode is not a function'.

Here is my component:

```vue
<script setup lang="ts">
import VueBarcode from '@chenfengyuan/vue-barcode';
</script>

<template>
    <vue-barcode value="5901234123457" :options="{ format: 'EAN13' }"></vue-barcode>
</template>
```

Browser shows these error messages:

![2022-08-14 08-59-32 的螢幕擷圖](https://user-images.githubusercontent.com/1922026/184518166-3405ab3d-59c1-45ed-9124-3909a46862c4.png)

And I installed JsBarcode for sure.

![2022-08-14 09-11-16 的螢幕擷圖](https://user-images.githubusercontent.com/1922026/184518540-4be8e2ce-3a0e-4258-8ebc-20513ef7859e.png)

**Comment by fengyuanchen** [comment]
How about registering the component as a global one? This works fine for me.

```js
import { createApp } from 'vue';
import VueBarcode from '@chenfengyuan/vue-barcode';

const app = createApp({});

app.component(VueBarcode.name, VueBarcode);
```

**Comment by Createitv** [comment]
Uncaught (in promise) TypeError: JsBarcode is not a function
The same as above。Vue3,2

**Comment by fengyuanchen** [comment]
You can load it by CDN:

```html
<script src="https://unpkg.com/vue@3"></script><!-- Vue.js is required -->
<script src="https://unpkg.com/jsbarcode@3/dist/JsBarcode.all.min.js"></script><!-- JsBarcode is required -->
<script src="https://unpkg.com/@chenfengyuan/vue-barcode@2"></script>
```

**Comment by twinroot** [comment]
This is still not working. I get the same error on Vue 3.

**Comment by stephen-morlex** [comment]
I'm also facing the same error on Vue3.

**Comment by fengyuanchen** [comment]
Works fine now with v2.0.1: https://codepen.io/cfy/pen/QWrogwB

**Comment by sroumaneextss** [comment]
Still facing the same error

**Comment by sroumaneextss** [comment]
I imported the component globally and i'm getting 

`JsBarcode is not a function`

`
    "@chenfengyuan/vue-barcode": "2",
    "jsbarcode": "3",
    "vue": "^3.2.37",
`

**Comment by sroumaneextss** [comment]
And why do you ask to install jsbarcode if your package has it as a dependency ?

**Comment by fengyuanchen** [comment]
> And why do you ask to install jsbarcode if your package has it as a dependency ?

`jsbarcode` is a **peer** dependency, but not dependency.

**Comment by MrLeihe** [comment]
don't works in vite
TypeError: JsBarcode is not a function

**Comment by fengyuanchen** [comment]
> don't works in vite TypeError: JsBarcode is not a function

Please check if the `jsbarcode` package is installed or not, if not, then run: `npm install jsbarcode`.

**Comment by lohchab** [comment]
don't works in vite despite JsBarcode installed.
TypeError: JsBarcode is not a function

**Comment by MLDMoritz** [comment]
This should not be closed, still bugged.
