### ISSUE TITLE
TypeError: JsBarcode is not a function

### ISSUE THREAD

**Issue by Sorry4Wait** [fengyuanchen/vue-barcode#17]
vite "vue": "3.2.25", "jsbarcode": "^3.11.5", "@chenfengyuan/vue-barcode": "^2.0.1"
TypeError: JsBarcode is not a function

**Comment by fengyuanchen** [comment]
Try to import the other file:

```js
import VueBarcode from '@chenfengyuan/vue-barcode/dist/vue-barcode'
```
