### ISSUE TITLE
options - text

### ISSUE THREAD

**Issue by nunob87** [fengyuanchen/vue-barcode#8]
hello, I want to have a barcode printed and underneath a text, but the text does not print

<barcode tag="svg" value="207795565798" text="test test test test"></barcode>
not print "test test test test"

thanks

**Comment by fengyuanchen** [comment]
You may need to set the `height` option to a large number too.

**Comment by nunob87** [comment]
does not print in the same text

**Comment by fengyuanchen** [comment]
You may need to check out the documentation of the [JsBarcode](https://github.com/lindell/JsBarcode).
